server:
  port: 8080
dotenv:
  enabled: true
  override: true

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
#    url: ${LOCAL_DB_URL}
#    username: ${LOCAL_DB_USERNAME}
#    password: ${LOCAL_DB_PASSWORD}
    url: ${DB_URL}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      initialization-fail-timeout: 0
      pool-name: RestaurantHikariPool

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        jdbc:
          time_zone: Asia/Yerevan

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

payment:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  idram:
    api-url: ${IDRAM_API_URL}
    api-key: ${IDRAM_API_KEY}
  easypay:
    api-url: ${EASYPAY_API_URL}
    api-key: ${EASYPAY_API_KEY}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate: DEBUG
    com.zaxxer.hikari: TRACE
